const express = require('express')
const positionsRouter = require('./positions')
const resumesRouter = require('./resumes')
const positionResumesRouter = require('./positionResumes')
const notesRouter = require('./notes')
const aiConfigsRouter = require('./aiConfigs')
const companiesRouter = require('./companies')
const flowLogsRouter = require('./flowLogs')
const interviewFlowRouter = require('./interviewFlow')
const interviewsRouter = require('./interviews')
const statsRouter = require('./stats')
const activitiesRouter = require('./activities')

const router = express.Router()

router.use('/positions', positionsRouter)
router.use('/positions', positionResumesRouter)
router.use('/positions', notesRouter)
router.use('/resumes', resumesRouter)
router.use('/ai-configs', aiConfigsRouter)
router.use('/companies', companiesRouter)
router.use('/flow-logs', flowLogsRouter)
router.use('/interview-flow', interviewFlowRouter)
router.use('/interviews', interviewsRouter)
router.use('/stats', statsRouter)
router.use('/activities', activitiesRouter)

module.exports = router
